# Generated by Django 2.2.5 on 2023-04-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20230416_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('Github', 'Github')], default='email', max_length=40),
        ),
    ]
