# Generated by Django 2.2.5 on 2023-04-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='house_rules',
        ),
        migrations.AddField(
            model_name='room',
            name='house_all_rules',
            field=models.ManyToManyField(null=True, to='rooms.HouseRule'),
        ),
    ]
